import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Box, Container } from "@mui/material";
import HeroSection from "@/components/heroSection";
import Services from "@/components/services";
import About from "@/components/aboutus";
import InfiniteMarquee from "@/components/infiniteText";
import Projects from "@/components/projects";
import Contact from "@/components/contact";
import RotatingCircle from "@/components/rotatingCircle";
import { COLORS } from "@/utils/color";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <div id="home">
          <HeroSection />
        </div>
        <div id="about">
          <About />
        </div>
        <Box
          sx={{
            backgroundColor: COLORS.DARKBLUE,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <RotatingCircle />
        </Box>
        <div id="services">
          <Services />
        </div>
        <div>
          <InfiniteMarquee />
        </div>
        <div id="projects">
          <Projects />
        </div>
        <div id="contact">
          <Contact />
        </div>
      </Box>
    </>
  );
}
