import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Box, Container } from "@mui/material";
import HeroSection from "@/components/heroSection";
import Services from "@/components/services";
import About from "@/components/aboutus";
import InfiniteMarquee from "@/components/infiniteText";
import Projects from "@/components/projects";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <HeroSection />
        <Box sx={{}}>
          <Services />
        </Box>
        <Box sx={{}}>
          <InfiniteMarquee />
        </Box>
        <Box sx={{}}>
          <About />
        </Box>
        <Box sx={{}}>
          <Projects />
        </Box>
      </Box>
    </>
  );
}
